---
 - name  : unzip
   hosts : df-prom-web01
   gather_facts: no
#   become : yes
#   become_method: runas
#   become_user: Administrator

   tasks : 

   - name : unzip and remuve arhive 
     win_shell : D:\unzip.ps1

 - name: test
   hosts: win_servers_prod
   gather_facts: no
   tasks:
   - include: stop.yml
  
#   - include: backup.yml

   - include : del_bin.yml

   - include_tasks: copy.yml
   
   - include: start.yml
